### PR TITLE
Extend github integration docs

### PR DESCRIPTION
**Pull request by lucasra1**
When trying to setup the github integration on my self-hosted sentry environment I noticed that it did not work. On further investigation I found out, that github threw an error. I got this error back from github [Github Doc](https://docs.github.com/en/apps/oauth-apps/maintaining-oauth-apps/troubleshooting-authorization-request-errors#redirect-uri-mismatch).

So I found out that I had to add the sentry github setup url to the callback list of my Github App. Extended Documentation to reflect this.

### CODE REVIEW

**Comment by JannKleen** [comment]
Thanks for finding this, I struggled adding the Github Integration because the second callback url was missing!

**Comment by aldy505** [comment]
Hey @hubertdeng123 @azaslavsky can you guys help out on this one, since this is not on the docs and caused the initial integration to be broken?

**Comment by aldy505** [comment]
Hey @cathteng can you also take a look over this one? Thanks!

**Review by hubertdeng123 — APPROVED** [review]

**Review by cathteng — APPROVED** [review]

**Comment by hubertdeng123** [comment]
@lucasra1 Could you rebase master here? Looks like some required CI jobs were added that need to be run

**Pull request merged**
