### PR TITLE
Update troubleshooting.mdx

### PR DESCRIPTION
**Pull request by yegorLitvinov**
Fix `nodestore_node` table name

### CODE REVIEW

**Comment by yegorLitvinov** [comment]
@chendo @BYK Could you please review this pr. 
Related PR is https://github.com/getsentry/develop/pull/388

**Review by BYK — APPROVED** [review]

**Comment by BYK** [comment]
Thanks a lot @yegorLitvinov!

**Comment by BYK** [comment]
Ping @chadwhitacre for unblocking the builds and merging.

**Comment by chadwhitacre** [comment]
Thanks @yegorLitvinov @BYK! :)

**Pull request merged**
