### PR TITLE
feat(bitbucket) Add on prem user docs

### PR DESCRIPTION
**Pull request by ceorourke**
Add instructions for how to use Bitbucket when running Sentry on prem. 

Screen Shot 2020-11-02 at 3 24 54 PM

### CODE REVIEW

**Review by manuzope — APPROVED** [review]

**Review by mgaeta — APPROVED** [review]
I think a example would help in the ngrok section. Like 
```
ngrok http -subdomain={YOUR_SUBDOMAIN} 80
```

**Comment by ceorourke** [comment]
@mgaeta I didn't update the screenshot but I added a link to the ngrok documentation on using a custom subdomain. Do you think I should have both?

**Comment by mgaeta** [comment]
Yeah I think seeing an example on the page will help a lot.

**Comment by mgaeta** [comment]
Looks great 👍

**Pull request merged**
