### PR TITLE
Update github.mdx

### PR DESCRIPTION
**Pull request by crayx**
Text edit for a repetitive set of words

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]
Thanks!

**Comment by ymeghna** [comment]
Thank you @AbhiPrasad !! thats my first commit to open source!

**Comment by crayx** [comment]
Thank you @AbhiPrasad! so excited, this is my first commit to open source

**Comment by AbhiPrasad** [comment]
First of many hopefully, appreciate the contribution :)

**Pull request merged**
