### PR TITLE
feat: Add PyCharm subpage

### PR DESCRIPTION
**Pull request by untitaker**
This is a copy of https://www.notion.so/sentry/Configuring-PyCharm-to-run-Sentry-dc7bc98abf5948ed9655a7c9d295ced4

Not too happy with the navbar:

Screenshot 2020-07-28 at 21 32 27

### CODE REVIEW

**Comment by dcramer** [comment]
What if we did "Editor Configuration -> PyCharm"

that would let us do anything else e.g. vim/vs code

**Comment by untitaker** [comment]
Like a top-level editor configuration section? idk how to do triple-nesting in the sidebar

**Comment by dcramer** [comment]
Oh right develop doesnt do that yet. We have dynamic done in docs I can port it over and we can rearrange this later.

**Comment by untitaker** [comment]
@dcramer wanna sign this off for now?

**Pull request merged**
