### PR TITLE
feat(sdk): rate-limit

### PR DESCRIPTION
**Pull request by bruno-garcia**

### CODE REVIEW

**Review by jan-auer — COMMENTED** [review]
@bruno-garcia Mind if I give this a full rewrite? I think this is still very hard to consume (it wasn't written with a public audience in mind), and it's missing some information on what scopes and categories are.

**Comment by bruno-garcia** [comment]
@jan-auer please do! Thank you

**Comment by bruno-garcia** [comment]
@jan-auer feel free to close this PR and open a new one if that's best for you

**Comment by jan-auer** [comment]
@bruno-garcia good point, will do that so that you can review and approve it. Thanks!

**Comment by bruno-garcia** [comment]
Can this be closed? @jan-auer

**Comment by bruno-garcia** [comment]
@jan-auer 👋

**Review by HazAT — APPROVED** [review]

**Comment by jan-auer** [comment]
Thanks, will pick this up soon.

**Comment by jan-auer** [comment]
Superseeded by https://github.com/getsentry/develop/pull/342

**Pull request closed without merging**
