### PR TITLE
docs(self-hosted): recommend users to rerun install.sh for restart

### PR DESCRIPTION
**Pull request by aldy505**
Closes [#2996](https://github.com/getsentry/self-hosted/issues/2996)

/cc @hubertdeng123 @azaslavsky @stayallive

### CODE REVIEW

**Comment by stayallive** [comment]
I'm trying to think on how to formulate this better, but I feel like the current suggestion is a bit "soft" as in that it's more of a suggestion while instead it's more of an requirement. Especially if config has been changed.

What about smth more like:

```
After changing configuration files re-run the <code>./install.sh</code> script to rebuild and restart the containers. See the <Link to="/self-hosted/#configuration">configuration section</Link> for more information.
```

(I would also make them all the same, now there are 3/4 versions of exactly the same thing worded slightly different)

**Comment by azaslavsky** [comment]
> I'm trying to think on how to formulate this better, but I feel like the current suggestion is a bit "soft" as in that it's more of a suggestion while instead it's more of an requirement. Especially if config has been changed.
> 
> What about smth more like:
> 
> ```
> After changing configuration files re-run the <code>./install.sh</code> script to rebuild and restart the containers. See the <Link to="/self-hosted/#configuration">configuration section</Link> for more information.
> ```
> 
> (I would also make them all the same, now there are 3/4 versions of exactly the same thing worded slightly different)

Agreed on both counts. We should replicate the exact same callout, and use language like "strongly recommended".

**Comment by aldy505** [comment]
What about now? @stayallive @azaslavsky

**Review by azaslavsky — APPROVED** [review]
LGTM!

**Comment by aldy505** [comment]
Ping @hubertdeng123

**Review by hubertdeng123 — APPROVED** [review]

**Pull request merged**
