### PR TITLE
feat(unified-api): Define `includeLocalVariables` option

### PR DESCRIPTION
**Pull request by AbhiPrasad**
Currently the PHP, Python, Ruby and NodeJS SDKs support local variables, but they all use inconsistent names for the option that gates this functionality.

- Ruby: [`capture_exception_frame_locals`](https://docs.sentry.io/platforms/ruby/configuration/options)
- Python: [`with_locals`](https://docs.sentry.io/platforms/python/configuration/options/#with-locals)
- PHP no option
- NodeJS [`_experiments.includeStackLocals`](https://docs.sentry.io/platforms/node/configuration/options/#_experiments.include-stack-locals)

I propose we rename this to `includeLocalVariables` / `include_local_variables`, unify these across the SDKs and add them when we get time

We also should decide if `sendDefaultPii` should have an affect on this.

cc @timfish

### CODE REVIEW

**Comment by antonpirker** [comment]
I like consistent naming, so I am in.

As this is only for errors should `error` be in the variable name? (bikesheding alarm)

**Comment by sl0thentr0py** [comment]
let's keep the PII stuff separate, I'm working on a comprehensive proposal to solve this better.
If that gets rejected, we can gate locals behind `sendDefaultPII` later.

**Review by sl0thentr0py — APPROVED** [review]
fine with me, but for existing implementations, we'll have to alias to existing names, deprecate them and remove them later in a major.

**Comment by AbhiPrasad** [comment]
> As this is only for errors should error be in the variable name

This is a good suggestion, but since I think local variables are a stacktrace concept, it should be clear to users that this only applies to errors.

**Comment by antonpirker** [comment]
Python issue for this: https://github.com/getsentry/sentry-python/issues/1854

**Pull request merged**
