### PR TITLE
Move frontend handbook to this repository

### PR DESCRIPTION
**Pull request by markstory**
Fewer places for documentation to live. I can archive the other repository if people are happy with this.

### CODE REVIEW

**Comment by dcramer** [comment]
:100:

**Comment by billyvg** [comment]
> This pull request is being automatically deployed with Vercel ([learn more](https://zeit.ink/github-learn-more)).
> To see the status of your deployment, click below or on the icon next to each commit.
> 
> 🔍 Inspect: [vercel.com/sentry/develop/pl85waodc/sentry.dev](https://vercel.com/sentry/develop/pl85waodc/sentry.dev)
> ✅ Preview: [develop-git-frontend-book.sentry.dev](https://develop-git-frontend-book.sentry.dev)

This inspect link doesn't work...? Maybe I don't have access, idk what it's supposed to be event

**Comment by markstory** [comment]
@dcramer I'm not able to merge this. Could you do that?

**Comment by markstory** [comment]
@dcramer I'm not able to merge this. Can you?

**Comment by dcramer** [comment]
disabled bors til its fixed

**Pull request merged**
